repos:
  - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier